---
- name: Install foreman services
  sudo: yes
  shell: bundle exec foreman export upstart /etc/init
         --port {{railsbox_port}}
         --user {{railsbox_user}}
         --app {{railsbox_application}}
         --procfile /home/{{railsbox_user}}/applications/{{railsbox_application}}/current/Procfile
         chdir="/home/{{railsbox_user}}/applications/{{railsbox_application}}/current"

- name: Start foreman services
  sudo: yes
  service: name={{railsbox_application}} enabled=yes state=started
